Added more OpenSSL versions to .travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -25,6 +25,9 @@ env:
   matrix:
     - OPENSSL_VERSION=1.1.0g
     - OPENSSL_VERSION=1.0.2n
+    - OPENSSL_VERSION=1.0.1u
+    - OPENSSL_VERSION=1.0.0s
+    - OPENSSL_VERSION=0.9.8zh
 
 cache:
   directories:
@@ -42,8 +45,11 @@ script:
     if [ ! -d openssl_version_cache/build/openssl-$OPENSSL_VERSION ]; then
       if [ ! -d openssl_version_cache/src/openssl-$OPENSSL_VERSION ]; then
         cd openssl_version_cache/src
-        tar xzf openssl-$OPENSSL_VERSION.tar.gz
+        tar xzf openssl-$OPENSSL_VERSION.tar.gz || exit 1
         cd ../..
+      fi
+      if [ ! -d openssl_version_cache/src/openssl-$OPENSSL_VERSION ]; then
+        echo "ERROR Dir openssl_version_cache/src/openssl-$OPENSSL_VERSION does not exist" && exit 1
       fi
       cd openssl_version_cache/src/openssl-$OPENSSL_VERSION
       ./Configure linux-x86_64 --prefix=$PWD/../../build/openssl-$OPENSSL_VERSION --openssldir=$PWD/../../build/openssl-$OPENSSL_VERSION/ssl enable-shared -Wa,--noexecstack > build.log 2>&1 || (cat build.log && exit 1)
